FROM docker.io/library/node:25.8-alpine3.23

VOLUME "/var/www/app/node_modules"
WORKDIR /var/www/app

COPY --chown=1001:1001 package*.json .
RUN npm install
COPY --chown=1001:1001 . .

EXPOSE 3000
STOPSIGNAL SIGTERM

USER 1001

CMD ["npm", "run", "dev"]
