FROM docker.io/library/python:3.14-alpine3.23

WORKDIR /var/www/app

COPY --chown=1001:1001 requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY --chown=1001:1001 . .

EXPOSE 5000
STOPSIGNAL SIGTERM

USER 1001

#CMD ["flask", "run"]
CMD ["python", "app.py"]